name: Generate Obsidian Graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Obsidian Graph
        uses: bissbert/obsidian-graph-github-action@v1
        with:
          python-version: "3.x"